// jobagent-vue-frontend/src/pages/CreateDomainPage.vue
<template>
  <div class="create-domain-page">
    <el-card class="domain-form-card">
      <template #header>
        <h1>Create Domain</h1>
      </template>
      
      <el-row :gutter="20">
        <el-col :span="12">
          <el-form-item label="Domain Title">
            <el-input
              v-model="domainStore.title"
              placeholder="Enter domain title (one word)"
              @input="handleTitleChange"
            />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="Domain Description">
            <el-input
              v-model="domainStore.description"
              type="textarea"
              :rows="3"
              placeholder="Describe how to diagnose failures in this domain"
            />
          </el-form-item>
        </el-col>
      </el-row>

      <el-alert
        v-if="domainStore.error"
        :title="domainStore.error"
        type="error"
        :closable="false"
        style="margin-bottom: 20px"
      />

      <div class="action-buttons">
        <el-button
          @click="handleSave(false)"
          :loading="domainStore.loading"
          :disabled="domainStore.loading"
        >
          <el-icon><Document /></el-icon>
          Save Draft
        </el-button>
        <el-button
          type="primary"
          @click="handleSave(true)"
          :loading="domainStore.loading"
          :disabled="domainStore.loading"
        >
          <el-icon><Upload /></el-icon>
          Publish
        </el-button>
      </div>
    </el-card>

    <el-row :gutter="20" class="workflow-section">
      <el-col :span="6">
        <el-card class="tools-panel">
          <template #header>
            <h3>Available Tools</h3>
          </template>
          
          <div v-loading="toolsStore.loading" class="tools-list">
            <div
              v-for="tool in toolsStore.availableTools"
              :key="tool.id"
              class="tool-item"
              draggable="true"
              @dragstart="handleDragStart(tool, $event)"
            >
              <el-tag type="info">{{ tool.title }}</el-tag>
            </div>
            
            <div class="create-tool-item">
              <el-button type="dashed" size="small">
                <el-icon><Plus /></el-icon>
                Create New Tool
              </el-button>
            </div>
          </div>
        </el-card>
      </el-col>

      <el-col :span="12">
        <el-card class="flow-builder">
          <template #header>
            <h3>Flow Builder</h3>
          </template>
          
          <div class="vue-flow-container">
            <VueFlow
              v-model:nodes="workflowStore.nodes"
              v-model:edges="workflowStore.edges"
              @node-click="handleNodeClick"
              @drop="handleDrop"
              @dragover="handleDragOver"
              class="vue-flow"
            >
              <Background />
              <Controls />
              
              <template #node-domain="{ data }">
                <div class="custom-node domain-node">
                  <div class="node-header">{{ data.title }}</div>
                  <div class="node-type">Domain</div>
                </div>
              </template>
              
              <template #node-mcp_tool="{ data, id }">
                <div class="custom-node tool-node">
                  <div class="node-header">
                    {{ data.title }}
                    <el-button
                      type="danger"
                      size="small"
                      text
                      @click="handleNodeDelete(id)"
                    >
                      <el-icon><Delete /></el-icon>
                    </el-button>
                  </div>
                  <div class="node-type">MCP Tool</div>
                </div>
              </template>
            </VueFlow>
          </div>
        </el-card>
      </el-col>

      <el-col :span="6">
        <el-card class="config-panel">
          <template #header>
            <h3>Configuration</h3>
          </template>
          
          <div v-if="workflowStore.selectedNode" class="node-config">
            <h4>{{ workflowStore.selectedNode.data.title }}</h4>
            <p class="node-type-label">
              {{ workflowStore.selectedNode.type === 'domain' ? 'Domain Configuration' : 'Tool Configuration' }}
            </p>
            
            <div v-if="workflowStore.selectedNode.type === 'domain'" class="domain-config">
              <el-form-item label="Title">
                <el-input
                  v-model="domainStore.title"
                  size="small"
                  @input="handleTitleChange"
                />
              </el-form-item>
              <el-form-item label="Description">
                <el-input
                  v-model="domainStore.description"
                  type="textarea"
                  :rows="3"
                  size="small"
                />
              </el-form-item>
            </div>
            
            <div v-else-if="selectedTool" class="tool-config">
              <el-form-item label="Parameters">
                <el-input
                  v-model="configJson"
                  type="textarea"
                  :rows="4"
                  size="small"
                  placeholder="Configure tool parameters (JSON)"
                  @input="handleConfigChange"
                />
              </el-form-item>
              <div class="api-url">
                <small>API URL: {{ selectedTool.api_url }}</small>
              </div>
            </div>
          </div>
          
          <div v-else class="no-selection">
            <p>Select a node to configure</p>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { VueFlow } from '@vue-flow/core'
import { Background } from '@vue-flow/background'
import { Controls } from '@vue-flow/controls'
import { Document, Upload, Plus, Delete } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'

import { useDomainStore } from '@/stores/domain'
import { useToolsStore } from '@/stores/tools'
import { useWorkflowStore } from '@/stores/workflow'
import { domainsAPI } from '@/utils/api'
import type { MCPTool, FlowNode } from '@/types'

const router = useRouter()
const domainStore = useDomainStore()
const toolsStore = useToolsStore()
const workflowStore = useWorkflowStore()

const configJson = ref('')

const selectedTool = computed(() => {
  if (!workflowStore.selectedNode || workflowStore.selectedNode.type !== 'mcp_tool') {
    return null
  }
  return toolsStore.getToolById(workflowStore.selectedNode.data.tool_id)
})

onMounted(() => {
  toolsStore.loadAvailableTools()
})

watch(() => workflowStore.selectedNode, (newNode) => {
  if (newNode && newNode.type === 'mcp_tool') {
    configJson.value = JSON.stringify(newNode.data.config || {}, null, 2)
  } else {
    configJson.value = ''
  }
})

const handleTitleChange = () => {
  workflowStore.updateDomainTitle(domainStore.title)
}

const handleDragStart = (tool: MCPTool, event: DragEvent) => {
  if (event.dataTransfer) {
    event.dataTransfer.setData('application/json', JSON.stringify(tool))
    event.dataTransfer.effectAllowed = 'copy'
  }
}

const handleDragOver = (event: DragEvent) => {
  event.preventDefault()
  if (event.dataTransfer) {
    event.dataTransfer.dropEffect = 'copy'
  }
}

const handleDrop = (event: DragEvent) => {
  event.preventDefault()
  
  try {
    const toolData = event.dataTransfer?.getData('application/json')
    if (!toolData) return
    
    const tool: MCPTool = JSON.parse(toolData)
    
    const newNode: FlowNode = {
      id: `tool_${Date.now()}`,
      type: 'mcp_tool',
      position: { x: event.offsetX - 75, y: event.offsetY - 25 },
      data: {
        title: tool.title,
        tool_id: tool.id,
        config: {}
      }
    }
    
    workflowStore.addNode(newNode)
  } catch (error) {
    console.error('Failed to parse dropped tool data:', error)
  }
}

const handleNodeClick = (event: any) => {
  workflowStore.selectNode(event.node.id)
}

const handleNodeDelete = (nodeId: string) => {
  workflowStore.removeNode(nodeId)
}

const handleConfigChange = () => {
  if (!workflowStore.selectedNode) return
  
  try {
    const config = JSON.parse(configJson.value)
    workflowStore.updateNodeData(workflowStore.selectedNode.id, { config })
  } catch (error) {
  }
}

const validateFlow = () => {
  const validationError = workflowStore.validateFlow(domainStore.title, domainStore.description)
  if (validationError) {
    domainStore.setError(validationError)
    return false
  }
  return true
}

const handleSave = async (publish = false) => {
  if (!validateFlow()) return

  domainStore.setLoading(true)
  domainStore.clearError()

  try {
    const flowConfig = workflowStore.getFlowConfig()

    const domainData = {
      title: domainStore.title,
      description: domainStore.description,
      flow_config: flowConfig,
      status: publish ? 'published' : 'draft'
    }

    await domainsAPI.createDomain(domainData)
    
    ElMessage.success(publish ? 'Domain published successfully!' : 'Domain saved as draft!')
    
    router.push('/')
  } catch (err: any) {
    const errorMessage = err.response?.data?.detail || 'Failed to save domain'
    domainStore.setError(errorMessage)
    ElMessage.error(errorMessage)
  } finally {
    domainStore.setLoading(false)
  }
}
</script>

<style scoped>
.create-domain-page {
  max-width: 1400px;
  margin: 0 auto;
  padding: 20px;
}

.domain-form-card {
  margin-bottom: 20px;
}

.action-buttons {
  display: flex;
  gap: 10px;
}

.workflow-section {
  min-height: 600px;
}

.tools-panel {
  height: 600px;
}

.tools-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.tool-item {
  cursor: move;
  padding: 8px;
  border: 1px solid #e4e7ed;
  border-radius: 4px;
  background: #f5f7fa;
  transition: background-color 0.3s;
}

.tool-item:hover {
  background: #e6f7ff;
}

.create-tool-item {
  margin-top: 10px;
}

.flow-builder {
  height: 600px;
}

.vue-flow-container {
  height: 520px;
  border: 2px dashed #d9d9d9;
  border-radius: 6px;
}

.vue-flow {
  height: 100%;
}

.custom-node {
  padding: 10px;
  border-radius: 6px;
  border: 2px solid #d9d9d9;
  background: white;
  min-width: 120px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.domain-node {
  background: #f6ffed;
  border-color: #52c41a;
}

.tool-node {
  background: #e6f7ff;
  border-color: #1890ff;
}

.node-header {
  font-weight: bold;
  font-size: 12px;
  margin-bottom: 4px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.node-type {
  font-size: 10px;
  color: #666;
}

.config-panel {
  height: 600px;
}

.node-config h4 {
  margin: 0 0 8px 0;
  font-size: 14px;
}

.node-type-label {
  font-size: 12px;
  color: #666;
  margin: 0 0 16px 0;
}

.api-url {
  margin-top: 8px;
  color: #666;
}

.no-selection {
  text-align: center;
  color: #999;
  margin-top: 50px;
}
</style>

// jobagent-frontend/src/pages/CreateDomainPage.tsx
import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { domainsAPI, mcpToolsAPI } from '../utils/api'
import { MCPTool } from '../types'
import { Save, Send, Plus, Trash2 } from 'lucide-react'

interface FlowNode {
  id: string
  type: 'domain' | 'mcp_tool'
  title: string
  x: number
  y: number
  config?: any
  tool_id?: number
}

const CreateDomainPage: React.FC = () => {
  const [domainTitle, setDomainTitle] = useState('')
  const [domainDescription, setDomainDescription] = useState('')
  const [availableTools, setAvailableTools] = useState<MCPTool[]>([])
  const [flowNodes, setFlowNodes] = useState<FlowNode[]>([
    { id: 'domain', type: 'domain', title: 'New Domain', x: 400, y: 100 }
  ])
  const [selectedNode, setSelectedNode] = useState<string | null>(null)
  const [draggedTool, setDraggedTool] = useState<MCPTool | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const navigate = useNavigate()

  useEffect(() => {
    loadAvailableTools()
  }, [])

  const loadAvailableTools = async () => {
    try {
      const response = await mcpToolsAPI.getTools({ status: 'published' })
      setAvailableTools(response.data)
    } catch (err) {
      console.error('Failed to load tools:', err)
    }
  }

  const handleDragStart = (tool: MCPTool) => {
    setDraggedTool(tool)
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    if (!draggedTool) return

    const rect = e.currentTarget.getBoundingClientRect()
    const x = e.clientX - rect.left
    const y = e.clientY - rect.top

    const newNode: FlowNode = {
      id: `tool_${Date.now()}`,
      type: 'mcp_tool',
      title: draggedTool.title,
      x: x - 75,
      y: y - 25,
      tool_id: draggedTool.id,
      config: {}
    }

    setFlowNodes([...flowNodes, newNode])
    setDraggedTool(null)
  }

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault()
  }

  const handleNodeClick = (nodeId: string) => {
    setSelectedNode(nodeId)
  }

  const handleNodeDelete = (nodeId: string) => {
    if (nodeId === 'domain') return
    setFlowNodes(flowNodes.filter(node => node.id !== nodeId))
    if (selectedNode === nodeId) {
      setSelectedNode(null)
    }
  }

  const updateNodeConfig = (nodeId: string, config: any) => {
    setFlowNodes(flowNodes.map(node => 
      node.id === nodeId ? { ...node, config } : node
    ))
  }

  const updateDomainNode = () => {
    setFlowNodes(flowNodes.map(node => 
      node.id === 'domain' ? { ...node, title: domainTitle || 'New Domain' } : node
    ))
  }

  useEffect(() => {
    updateDomainNode()
  }, [domainTitle])

  const validateFlow = () => {
    if (!domainTitle.trim()) {
      setError('Domain title is required')
      return false
    }
    if (!domainDescription.trim()) {
      setError('Domain description is required')
      return false
    }
    
    for (const node of flowNodes) {
      if (node.type === 'mcp_tool' && (!node.config || Object.keys(node.config).length === 0)) {
        setError(`Please configure the "${node.title}" tool`)
        return false
      }
    }
    
    return true
  }

  const handleSave = async (publish = false) => {
    if (!validateFlow()) return

    setLoading(true)
    setError('')

    try {
      const flowConfig = {
        nodes: flowNodes,
        connections: []
      }

      const domainData = {
        title: domainTitle,
        description: domainDescription,
        flow_config: flowConfig,
        status: publish ? 'published' : 'draft'
      }

      await domainsAPI.createDomain(domainData)
      navigate('/')
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to save domain')
    } finally {
      setLoading(false)
    }
  }

  const selectedNodeData = selectedNode ? flowNodes.find(n => n.id === selectedNode) : null
  const selectedTool = selectedNodeData?.tool_id ? 
    availableTools.find(t => t.id === selectedNodeData.tool_id) : null

  return (
    <div className="max-w-7xl mx-auto">
      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h1 className="text-2xl font-bold text-gray-900 mb-6">Create Domain</h1>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Domain Title
            </label>
            <input
              type="text"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Enter domain title (one word)"
              value={domainTitle}
              onChange={(e) => setDomainTitle(e.target.value)}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Domain Description
            </label>
            <textarea
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Describe how to diagnose failures in this domain"
              rows={3}
              value={domainDescription}
              onChange={(e) => setDomainDescription(e.target.value)}
            />
          </div>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-md p-4 mb-6">
            <span className="text-red-700">{error}</span>
          </div>
        )}

        <div className="flex space-x-4 mb-6">
          <button
            onClick={() => handleSave(false)}
            disabled={loading}
            className="bg-gray-600 text-white px-4 py-2 rounded-md hover:bg-gray-700 disabled:opacity-50 flex items-center"
          >
            <Save className="w-4 h-4 mr-2" />
            Save Draft
          </button>
          <button
            onClick={() => handleSave(true)}
            disabled={loading}
            className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 disabled:opacity-50 flex items-center"
          >
            <Send className="w-4 h-4 mr-2" />
            Publish
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <div className="bg-white rounded-lg shadow-md p-4">
          <h3 className="text-lg font-semibold mb-4">Available Tools</h3>
          <div className="space-y-2">
            {availableTools.map((tool) => (
              <div
                key={tool.id}
                draggable
                onDragStart={() => handleDragStart(tool)}
                className="bg-blue-100 p-3 rounded-md cursor-move hover:bg-blue-200 transition-colors"
              >
                <div className="font-medium text-sm">{tool.title}</div>
              </div>
            ))}
            <div className="bg-gray-100 p-3 rounded-md cursor-pointer hover:bg-gray-200 transition-colors flex items-center">
              <Plus className="w-4 h-4 mr-2" />
              <span className="text-sm">Create New Tool</span>
            </div>
          </div>
        </div>

        <div className="lg:col-span-2 bg-white rounded-lg shadow-md p-4">
          <h3 className="text-lg font-semibold mb-4">Flow Builder</h3>
          <div
            className="relative bg-gray-50 border-2 border-dashed border-gray-300 rounded-lg h-96 overflow-hidden"
            onDrop={handleDrop}
            onDragOver={handleDragOver}
          >
            {flowNodes.map((node) => (
              <div
                key={node.id}
                className={`absolute bg-white border-2 rounded-lg p-3 cursor-pointer shadow-sm ${
                  selectedNode === node.id ? 'border-blue-500' : 'border-gray-300'
                } ${node.type === 'domain' ? 'bg-green-100' : 'bg-blue-100'}`}
                style={{ left: node.x, top: node.y, width: '150px' }}
                onClick={() => handleNodeClick(node.id)}
              >
                <div className="flex justify-between items-start">
                  <div className="text-sm font-medium truncate">{node.title}</div>
                  {node.type !== 'domain' && (
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        handleNodeDelete(node.id)
                      }}
                      className="text-red-500 hover:text-red-700"
                    >
                      <Trash2 className="w-3 h-3" />
                    </button>
                  )}
                </div>
                <div className="text-xs text-gray-500 mt-1">
                  {node.type === 'domain' ? 'Domain' : 'MCP Tool'}
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-md p-4">
          <h3 className="text-lg font-semibold mb-4">Configuration</h3>
          {selectedNodeData ? (
            <div>
              <div className="mb-4">
                <h4 className="font-medium text-sm mb-2">{selectedNodeData.title}</h4>
                <p className="text-xs text-gray-500">
                  {selectedNodeData.type === 'domain' ? 'Domain Configuration' : 'Tool Configuration'}
                </p>
              </div>
              
              {selectedNodeData.type === 'domain' ? (
                <div className="space-y-3">
                  <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">Title</label>
                    <input
                      type="text"
                      className="w-full px-2 py-1 text-sm border border-gray-300 rounded"
                      value={domainTitle}
                      onChange={(e) => setDomainTitle(e.target.value)}
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">Description</label>
                    <textarea
                      className="w-full px-2 py-1 text-sm border border-gray-300 rounded"
                      rows={3}
                      value={domainDescription}
                      onChange={(e) => setDomainDescription(e.target.value)}
                    />
                  </div>
                </div>
              ) : selectedTool ? (
                <div className="space-y-3">
                  <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">Parameters</label>
                    <textarea
                      className="w-full px-2 py-1 text-sm border border-gray-300 rounded"
                      rows={4}
                      placeholder="Configure tool parameters (JSON)"
                      value={JSON.stringify(selectedNodeData.config || {}, null, 2)}
                      onChange={(e) => {
                        try {
                          const config = JSON.parse(e.target.value)
                          updateNodeConfig(selectedNodeData.id, config)
                        } catch (err) {
                        }
                      }}
                    />
                  </div>
                  <div className="text-xs text-gray-500">
                    API URL: {selectedTool.api_url}
                  </div>
                </div>
              ) : null}
            </div>
          ) : (
            <p className="text-sm text-gray-500">Select a node to configure</p>
          )}
        </div>
      </div>
    </div>
  )
}

export default CreateDomainPage
