// jobagent-frontend/src/pages/MCPToolsPage.tsx
import React, { useState, useEffect } from 'react'
import { mcpToolsAPI } from '../utils/api'
import { MCPTool } from '../types'
import { Plus, Edit, Play, Eye, MessageSquare, CheckCircle, Clock, AlertCircle } from 'lucide-react'

const MCPToolsPage: React.FC = () => {
  const [tools, setTools] = useState<MCPTool[]>([])
  const [showCreateForm, setShowCreateForm] = useState(false)
  const [selectedTool, setSelectedTool] = useState<MCPTool | null>(null)
  const [testParameters, setTestParameters] = useState('')
  const [testResult, setTestResult] = useState<any>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [filter, setFilter] = useState<'all' | 'my_tools' | 'published'>('my_tools')

  const [newTool, setNewTool] = useState({
    title: '',
    api_url: '',
    parameters: ''
  })

  useEffect(() => {
    loadTools()
  }, [filter])

  const loadTools = async () => {
    try {
      const params = filter === 'my_tools' ? { my_tools: true } : 
                   filter === 'published' ? { status: 'published' } : {}
      const response = await mcpToolsAPI.getTools(params)
      setTools(response.data)
    } catch (err) {
      console.error('Failed to load tools:', err)
    }
  }

  const handleCreateTool = async () => {
    if (!newTool.title || !newTool.api_url) {
      setError('Title and API URL are required')
      return
    }

    setLoading(true)
    setError('')

    try {
      let parameters = {}
      if (newTool.parameters.trim()) {
        parameters = JSON.parse(newTool.parameters)
      }

      await mcpToolsAPI.createTool({
        title: newTool.title,
        api_url: newTool.api_url,
        parameters
      })

      setNewTool({ title: '', api_url: '', parameters: '' })
      setShowCreateForm(false)
      loadTools()
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to create tool')
    } finally {
      setLoading(false)
    }
  }

  const handleTestTool = async (tool: MCPTool) => {
    if (!testParameters.trim()) {
      setError('Please provide test parameters')
      return
    }

    setLoading(true)
    setError('')
    setTestResult(null)

    try {
      const parameters = JSON.parse(testParameters)
      const response = await mcpToolsAPI.executeTool(tool.id, parameters)
      setTestResult(response.data)
      
      if (response.data.success) {
        await mcpToolsAPI.updateTool(tool.id, { sample_input: parameters })
        loadTools()
      }
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to test tool')
    } finally {
      setLoading(false)
    }
  }

  const handleReleaseTool = async (tool: MCPTool) => {
    if (!tool.sample_input) {
      setError('Please test the tool successfully before releasing')
      return
    }

    setLoading(true)
    try {
      await mcpToolsAPI.updateTool(tool.id, { status: 'waiting_for_admin_review' })
      loadTools()
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to release tool')
    } finally {
      setLoading(false)
    }
  }

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'published':
        return <CheckCircle className="w-4 h-4 text-green-500" />
      case 'waiting_for_admin_review':
        return <Clock className="w-4 h-4 text-yellow-500" />
      default:
        return <AlertCircle className="w-4 h-4 text-gray-500" />
    }
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'published':
        return 'bg-green-100 text-green-800'
      case 'waiting_for_admin_review':
        return 'bg-yellow-100 text-yellow-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  return (
    <div className="max-w-6xl mx-auto">
      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold text-gray-900">MCP Tools</h1>
          <button
            onClick={() => setShowCreateForm(true)}
            className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 flex items-center"
          >
            <Plus className="w-4 h-4 mr-2" />
            Create New Tool
          </button>
        </div>

        <div className="flex space-x-4 mb-6">
          <button
            onClick={() => setFilter('my_tools')}
            className={`px-4 py-2 rounded-md ${filter === 'my_tools' ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-700'}`}
          >
            My Tools
          </button>
          <button
            onClick={() => setFilter('published')}
            className={`px-4 py-2 rounded-md ${filter === 'published' ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-700'}`}
          >
            Published Tools
          </button>
          <button
            onClick={() => setFilter('all')}
            className={`px-4 py-2 rounded-md ${filter === 'all' ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-700'}`}
          >
            All Tools
          </button>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-md p-4 mb-6">
            <span className="text-red-700">{error}</span>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {tools.map((tool) => (
            <div key={tool.id} className="border border-gray-200 rounded-lg p-4">
              <div className="flex justify-between items-start mb-3">
                <h3 className="font-semibold text-lg">{tool.title}</h3>
                <div className="flex items-center">
                  {getStatusIcon(tool.status)}
                  <span className={`ml-1 px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(tool.status)}`}>
                    {tool.status}
                  </span>
                </div>
              </div>
              
              <p className="text-sm text-gray-600 mb-3">{tool.api_url}</p>
              
              {tool.admin_comments && (
                <div className="bg-yellow-50 border border-yellow-200 rounded-md p-3 mb-3">
                  <div className="flex items-start">
                    <MessageSquare className="w-4 h-4 text-yellow-600 mr-2 mt-0.5" />
                    <div>
                      <p className="text-sm font-medium text-yellow-800">Admin Comments:</p>
                      <p className="text-sm text-yellow-700">{tool.admin_comments}</p>
                    </div>
                  </div>
                </div>
              )}
              
              <div className="flex space-x-2">
                <button
                  onClick={() => setSelectedTool(tool)}
                  className="flex-1 bg-gray-100 text-gray-700 px-3 py-2 rounded text-sm hover:bg-gray-200 flex items-center justify-center"
                >
                  <Eye className="w-3 h-3 mr-1" />
                  View
                </button>
                <button
                  onClick={() => {
                    setSelectedTool(tool)
                    setTestParameters(JSON.stringify(tool.sample_input || {}, null, 2))
                  }}
                  className="flex-1 bg-blue-100 text-blue-700 px-3 py-2 rounded text-sm hover:bg-blue-200 flex items-center justify-center"
                >
                  <Play className="w-3 h-3 mr-1" />
                  Test
                </button>
                {tool.status === 'draft' && tool.sample_input && (
                  <button
                    onClick={() => handleReleaseTool(tool)}
                    disabled={loading}
                    className="flex-1 bg-green-100 text-green-700 px-3 py-2 rounded text-sm hover:bg-green-200 disabled:opacity-50"
                  >
                    Release
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {showCreateForm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <h2 className="text-xl font-bold mb-4">Create New MCP Tool</h2>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Title</label>
                <input
                  type="text"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  value={newTool.title}
                  onChange={(e) => setNewTool({ ...newTool, title: e.target.value })}
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">API URL</label>
                <input
                  type="url"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  value={newTool.api_url}
                  onChange={(e) => setNewTool({ ...newTool, api_url: e.target.value })}
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Parameters (JSON)</label>
                <textarea
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  rows={4}
                  placeholder='{"param1": "type", "param2": "type"}'
                  value={newTool.parameters}
                  onChange={(e) => setNewTool({ ...newTool, parameters: e.target.value })}
                />
              </div>
            </div>
            
            <div className="flex space-x-3 mt-6">
              <button
                onClick={() => setShowCreateForm(false)}
                className="flex-1 bg-gray-300 text-gray-700 px-4 py-2 rounded-md hover:bg-gray-400"
              >
                Cancel
              </button>
              <button
                onClick={handleCreateTool}
                disabled={loading}
                className="flex-1 bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 disabled:opacity-50"
              >
                {loading ? 'Creating...' : 'Create'}
              </button>
            </div>
          </div>
        </div>
      )}

      {selectedTool && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-2xl max-h-96 overflow-y-auto">
            <h2 className="text-xl font-bold mb-4">{selectedTool.title}</h2>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">API URL</label>
                <p className="text-sm bg-gray-50 p-2 rounded">{selectedTool.api_url}</p>
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Test Parameters</label>
                <textarea
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  rows={4}
                  value={testParameters}
                  onChange={(e) => setTestParameters(e.target.value)}
                />
              </div>
              
              {testResult && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Test Result</label>
                  <div className={`p-3 rounded-md ${testResult.success ? 'bg-green-50 border border-green-200' : 'bg-red-50 border border-red-200'}`}>
                    <pre className="text-sm whitespace-pre-wrap">
                      {testResult.success ? 
                        JSON.stringify(testResult.response, null, 2) : 
                        testResult.error
                      }
                    </pre>
                  </div>
                </div>
              )}
            </div>
            
            <div className="flex space-x-3 mt-6">
              <button
                onClick={() => {
                  setSelectedTool(null)
                  setTestParameters('')
                  setTestResult(null)
                }}
                className="flex-1 bg-gray-300 text-gray-700 px-4 py-2 rounded-md hover:bg-gray-400"
              >
                Close
              </button>
              <button
                onClick={() => handleTestTool(selectedTool)}
                disabled={loading}
                className="flex-1 bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 disabled:opacity-50"
              >
                {loading ? 'Testing...' : 'Test Tool'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default MCPToolsPage

// jobagent-frontend/src/pages/MCPToolsPage.vue
<template>
  <div class="max-w-6xl mx-auto">
    <div class="bg-white rounded-lg shadow-md p-6 mb-6">
      <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold text-gray-900">MCP Tools Management</h1>
        <el-button type="primary" @click="showCreateDialog = true">
          <el-icon class="mr-2"><Plus /></el-icon>
          Create New Tool
        </el-button>
      </div>

      <el-tabs v-model="activeTab" class="demo-tabs">
        <el-tab-pane label="My Tools" name="my">
          <el-table :data="myTools" :loading="loading" stripe>
            <el-table-column prop="title" label="Title" width="200" />
            <el-table-column prop="api_url" label="API URL" show-overflow-tooltip />
            <el-table-column prop="status" label="Status" width="150">
              <template #default="scope">
                <el-tag :type="getStatusType(scope.row.status)">
                  {{ scope.row.status }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="created_at" label="Created" width="150">
              <template #default="scope">
                {{ formatDate(scope.row.created_at) }}
              </template>
            </el-table-column>
            <el-table-column label="Actions" width="200">
              <template #default="scope">
                <el-button size="small" @click="editTool(scope.row)">Edit</el-button>
                <el-button size="small" @click="deleteTool(scope.row)">Delete</el-button>
                <el-button size="small" type="success" @click="testTool(scope.row)">Test</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>

        <el-tab-pane label="Published Tools" name="published">
          <el-table :data="publishedTools" :loading="loading" stripe>
            <el-table-column prop="title" label="Title" width="200" />
            <el-table-column prop="api_url" label="API URL" show-overflow-tooltip />
            <el-table-column prop="created_at" label="Published" width="150">
              <template #default="scope">
                {{ formatDate(scope.row.created_at) }}
              </template>
            </el-table-column>
            <el-table-column label="Actions" width="150">
              <template #default="scope">
                <el-button size="small" type="success" @click="testTool(scope.row)">Test</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>
      </el-tabs>
    </div>

    <el-dialog 
      v-model="showCreateDialog" 
      title="Create New MCP Tool" 
      width="600px"
      @open="handleCreateDialogOpen"
    >
      <el-form ref="formRef" :model="toolForm" :rules="toolRules" label-width="120px">
        <el-form-item label="Title" prop="title">
          <el-input v-model="toolForm.title" placeholder="Enter tool title" />
        </el-form-item>
        
        <el-form-item label="API URL" prop="api_url">
          <el-input v-model="toolForm.api_url" placeholder="Enter API URL" />
        </el-form-item>
        
        <el-form-item label="Parameters">
          <div class="parameters-container">
            <div v-for="(param, index) in parametersList" :key="index" class="parameter-row">
              <el-input 
                v-model="param.name" 
                placeholder="Parameter name" 
                class="param-name"
              />
              <el-select 
                v-model="param.type" 
                placeholder="Type"
                class="param-type"
              >
                <el-option 
                  v-for="type in parameterTypes" 
                  :key="type.value" 
                  :label="type.label" 
                  :value="type.value" 
                />
              </el-select>
              <el-checkbox v-model="param.required" label="Required" class="param-required" />
              <el-button 
                type="danger" 
                circle 
                @click="removeParameter(index)" 
                :icon="Delete"
                class="param-delete"
              />
            </div>
            
            <div class="add-param-row">
              <el-button type="primary" @click="addParameter" plain>
                <el-icon class="mr-1"><Plus /></el-icon>
                Add Parameter
              </el-button>
            </div>
          </div>
        </el-form-item>
        
        <el-form-item label="JSON Preview" v-if="parametersList.length > 0">
          <el-input
            v-model="parametersJson"
            type="textarea"
            :rows="4"
            readonly
            placeholder="Parameters JSON preview"
          />
        </el-form-item>
      </el-form>
      
      <template #footer>
        <el-button @click="showCreateDialog = false">Cancel</el-button>
        <el-button type="primary" :loading="creating" @click="createTool">Create</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="showTestDialog" title="Test MCP Tool" width="600px">
      <div v-if="testingTool">
        <h3 class="mb-4">{{ testingTool.title }}</h3>
        <el-form label-width="120px">
          <el-form-item label="Test Parameters">
            <el-input
              v-model="testParameters"
              type="textarea"
              :rows="4"
              placeholder="Enter test parameters as JSON"
            />
          </el-form-item>
        </el-form>
        
        <div v-if="testResult" class="mt-4">
          <h4 class="mb-2">Test Result:</h4>
          <el-alert
            :type="testResult.success ? 'success' : 'error'"
            :title="testResult.success ? 'Success' : 'Error'"
            show-icon
          >
            <pre class="mt-2">{{ testResult.data }}</pre>
          </el-alert>
        </div>
      </div>
      
      <template #footer>
        <el-button @click="showTestDialog = false">Close</el-button>
        <el-button type="primary" :loading="testing" @click="runTest">Run Test</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { Plus, Delete } from '@element-plus/icons-vue'
import { mcpToolsAPI } from '@/utils/api'
import type { MCPTool } from '@/types'



const activeTab = ref('my')
const myTools = ref<MCPTool[]>([])
const publishedTools = ref<MCPTool[]>([])
const loading = ref(false)
const creating = ref(false)
const testing = ref(false)

const showCreateDialog = ref(false)
const showTestDialog = ref(false)
const testingTool = ref<MCPTool | null>(null)
const testParameters = ref('')
const testResult = ref<any>(null)

const formRef = ref<FormInstance>()
const toolForm = ref({
  title: '',
  api_url: '',
  parameters: {}
})

// 参数列表，用于UI显示和交互
const parametersList = ref<Array<{name: string, type: string, required: boolean}>>([])

// 可选的参数类型
const parameterTypes = [
  { label: 'String (str)', value: 'str' },
  { label: 'Integer (int)', value: 'int' },
  { label: 'Float', value: 'float' },
  { label: 'Boolean (bool)', value: 'bool' },
  { label: 'List', value: 'list' },
  { label: 'Dictionary (dict)', value: 'dict' }
]

// 添加新参数
const addParameter = () => {
  parametersList.value.push({ name: '', type: 'str', required: false })
}

// 删除参数
const removeParameter = (index: number) => {
  parametersList.value.splice(index, 1)
}

// 将参数列表转换为JSON对象
const updateParametersJson = () => {
  const params: Record<string, any> = {}
  parametersList.value.forEach(param => {
    if (param.name.trim()) {
      params[param.name] = {
        type: param.type,
        required: param.required
      }
    }
  })
  return params
}

// 监听对话框打开，初始化参数列表
const handleCreateDialogOpen = () => {
  // 清空参数列表
  parametersList.value = []
  // 添加一个空参数作为起点
  addParameter()
}

// 用于存储JSON字符串，但现在主要用于内部转换
const parametersJson = computed(() => {
  return JSON.stringify(updateParametersJson(), null, 2)
})

const toolRules: FormRules = {
  title: [
    { required: true, message: 'Title is required', trigger: 'blur' }
  ],
  api_url: [
    { required: true, message: 'API URL is required', trigger: 'blur' }
  ]
}

onMounted(() => {
  loadTools()
})

const loadTools = async () => {
  loading.value = true
  try {
    const [myResponse, publishedResponse] = await Promise.all([
      mcpToolsAPI.getTools({ my_tools: true }),
      mcpToolsAPI.getTools({ status: 'published' })
    ])
    myTools.value = myResponse.data
    publishedTools.value = publishedResponse.data
  } catch (err) {
    ElMessage.error('Failed to load tools')
  } finally {
    loading.value = false
  }
}

const createTool = async () => {
  if (!formRef.value) return
  
  const valid = await formRef.value.validate().catch(() => false)
  if (!valid) return

  // 检查参数名称是否为空
  const emptyParams = parametersList.value.filter(param => !param.name.trim())
  if (emptyParams.length > 0) {
    ElMessage.warning('Parameter names cannot be empty')
    return
  }

  // 使用更新后的参数
  toolForm.value.parameters = updateParametersJson()

  creating.value = true
  try {
    await mcpToolsAPI.createTool(toolForm.value)
    ElMessage.success('Tool created successfully')
    showCreateDialog.value = false
    toolForm.value = { title: '', api_url: '', parameters: {} }
    parametersList.value = []
    loadTools()
  } catch (err: any) {
    ElMessage.error(err.response?.data?.detail || 'Failed to create tool')
  } finally {
    creating.value = false
  }
}

const editTool = (tool: MCPTool) => {
  ElMessage.info('Edit functionality coming soon')
}

const testTool = (tool: MCPTool) => {
  testingTool.value = tool
  testParameters.value = JSON.stringify(tool.sample_input || {}, null, 2)
  testResult.value = null
  showTestDialog.value = true
}

const deleteTool = (tool: MCPTool) => {
  ElMessageBox.confirm(
    `Are you sure you want to delete the tool "${tool.title}"?`,
    'Warning',
    {
      confirmButtonText: 'Delete',
      cancelButtonText: 'Cancel',
      type: 'warning',
    }
  )
    .then(async () => {
      loading.value = true
      try {
        await mcpToolsAPI.deleteTool(tool.id)
        ElMessage.success('Tool deleted successfully')
        // 重新加载工具列表
        loadTools()
      } catch (err: any) {
        ElMessage.error(err.response?.data?.detail || 'Failed to delete tool')
      } finally {
        loading.value = false
      }
    })
    .catch(() => {
      // 用户取消删除操作
    })
}

const runTest = async () => {
  if (!testingTool.value) return

  let params
  try {
    params = JSON.parse(testParameters.value)
  } catch (err) {
    ElMessage.error('Invalid JSON in test parameters')
    return
  }

  testing.value = true
  try {
    const response = await mcpToolsAPI.executeTool(testingTool.value.id, params)
    testResult.value = {
      success: true,
      data: JSON.stringify(response.data, null, 2)
    }
  } catch (err: any) {
    testResult.value = {
      success: false,
      data: err.response?.data?.detail || 'Test failed'
    }
  } finally {
    testing.value = false
  }
}

const getStatusType = (status: string) => {
  switch (status) {
    case 'published':
      return 'success'
    case 'waiting_for_admin_review':
      return 'warning'
    case 'draft':
      return 'info'
    default:
      return 'info'
  }
}

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString()
}
</script>

<style scoped>
.el-card {
  border-radius: 8px;
}

/* 参数表单样式 */
.parameters-container {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.parameter-row {
  display: flex;
  align-items: center;
  gap: 10px;
}

.param-name {
  flex: 2;
  min-width: 150px;
}

.param-type {
  flex: 1;
  min-width: 120px;
}

.param-required {
  flex: 0.8;
  min-width: 100px;
}

.param-delete {
  flex: 0 0 auto;
}

.add-param-row {
  margin-top: 8px;
}

/* 预览JSON区域样式 */
.el-textarea.is-readonly .el-textarea__inner {
  background-color: #f5f7fa;
  color: #606266;
}
</style>
